### ISSUE TITLE
Feature tracker

### ISSUE THREAD

**Issue by bloodbornebi** [bloodbornebi/polyatomic_quiz#3]
Make a tracker to keep the things which-are-coming updated
- [ ] Make basic list
- [ ] Research git API
- [ ] Make list which updates automatically
